name: Python continuous-integration
on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up de Python '3.12.5'
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.5'
            - name: Instala las dependencias
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
            - name: Test con pytest
              run: |
                  pytest
